### ISSUE TITLE
After update continius crash

### ISSUE THREAD

**Issue by Sturmkater** [telegram-sms/telegram-sms#35]
I did update to the last version on github, but now i have it crash every minut:
```
type: crash
osVersion: google/shiba/shiba:14/AP2A.240905.003/2024101200:user/release-keys
package: com.qwe7002.telegram_sms:4878
process: com.qwe7002.telegram_sms:command
processUptime: 1237 + 1795 ms
installer: com.android.packageinstaller

java.lang.RuntimeException: Unable to create service com.qwe7002.telegram_sms.chat_command_service: java.lang.SecurityException: com.qwe7002.telegram_sms: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4942)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2414)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.SecurityException: com.qwe7002.telegram_sms: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3192)
	at android.os.Parcel.createException(Parcel.java:3176)
	at android.os.Parcel.readException(Parcel.java:3152)
	at android.os.Parcel.readException(Parcel.java:3094)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5898)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1885)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1825)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1813)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:757)
	at com.qwe7002.telegram_sms.chat_command_service.onCreate(chat_command_service.java:514)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4929)
	... 11 more
```

**Comment by qwe7002** [comment]
We have confirmed this issue and are working on a fix.Thank you for your feedback
